export const SET_REALTIME_RANK_CHOICE = "SET_REALTIME_RANK_CHOICE";
export const SET_MONTH_NEW_WEBTOON = "SET_MONTH_NEW_WEBTOON";
export const SET_WEEKDAY_RECOMMEND_WEBTOON = "SET_WEEKDAY_RECOMMEND_WEBTOON";
export const SET_ALL_WEBTOONS = "SET_ALL_WEBTOONS";
export const SET_WEBTOONS_BY_GENRE = "SET_WEBTOONS_BY_GENRE";
